{{/*
  Machine templates are immutable, so we need to make a new one when the spec changes.
  To do this, we create a new template whenever the checksum of the spec changes.
*/}}
{{- define "openstack-cluster.controlplane.mt.spec" -}}
{{-
  $blockDevices :=
    not (not .Values.etcd.blockDevice) |
    ternary (dict "etcd" .Values.etcd.blockDevice) dict |
    mergeOverwrite .Values.controlPlane.additionalBlockDevices
}}
template:
  spec:
    identityRef:
      name: {{ include "openstack-cluster.cloudCredentialsSecretName" . }}
      cloudName: openstack
    flavor: {{ .Values.controlPlane.machineFlavor | required ".Values.controlPlane.machineFlavor is required" }}
    {{- with .Values.machineSSHKeyName }}
    sshKeyName: {{ . }}
    {{- end }}
    {{- if or .Values.controlPlane.machineConfigDrive $blockDevices }}
    configDrive: true
    {{- end }}
    {{- with .Values.controlPlane.machineRootVolume }}
    {{- if .diskSize }}
    rootVolume:
      sizeGiB: {{ .diskSize }}
      {{- with .volumeType }}
      type: {{ . }}
      {{- end }}
      availabilityZone:
        {{- if .availabilityZone }}
        from: Name
        name: {{ .availabilityZone }}
        {{- else }}
        from: Machine
        {{- end }}
    {{- end }}
    {{- end }}
    image:
      {{- if .Values.controlPlane.machineImageId }}
      id: {{ .Values.controlPlane.machineImageId }}
      {{- else if .Values.controlPlane.machineImage }}
      filter:
        name: {{ tpl .Values.controlPlane.machineImage . }}
      {{- else if .Values.machineImageId }}
      id: {{ .Values.machineImageId }}
      {{- else if .Values.machineImage }}
      filter:
        name: {{ tpl .Values.machineImage . }}
      {{- else }}
      {{- fail "One of controlPlane.machineImageId, controlPlane.machineImage, machineImageId or machineImage is required" }}
      {{- end }}
    {{- with $blockDevices }}
    additionalBlockDevices:
      {{- range $name, $blockDevice := . }}
      - name: {{ $name }}
        sizeGiB: {{ required "size is required for a block device" $blockDevice.size }}
        storage:
          type: {{ default "Volume" $blockDevice.type }}
          volume:
            {{- with $blockDevice.volumeType }}
            type: {{ . }}
            {{- end }}
            availabilityZone:
              {{- if $blockDevice.availabilityZone }}
              from: Name
              name: {{ $blockDevice.availabilityZone }}
              {{- else }}
              from: Machine
              {{- end }}
      {{- end }}
    {{- end }}
    {{- with .Values.controlPlane.machineNetworking.ports }}
    ports: {{ include "openstack-cluster.convert.neutronPortsFilter" . | nindent 6 }}
    {{- end }}
    {{- with .Values.controlPlane.serverGroupId }}
    serverGroup:
      id: {{ . }}
    {{- end }}
    {{- with mergeOverwrite .Values.machineMetadata .Values.controlPlane.machineMetadata }}
    serverMetadata:
      {{- range $k, $v := . }}
      - key: {{ quote $k }}
        value: {{ quote $v }}
      {{- end }}
    {{- end }}
{{- end }}

{{- define "openstack-cluster.controlplane.mt.checksum" -}}
{{- include "openstack-cluster.controlplane.mt.spec" . | sha256sum }}
{{- end }}

{{- define "openstack-cluster.controlplane.mt.name" -}}
{{- $checksum := include "openstack-cluster.controlplane.mt.checksum" . }}
{{- include "openstack-cluster.componentName" (list . "control-plane") }}-{{ trunc 8 $checksum }}
{{- end }}

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: {{ include "openstack-cluster.controlplane.mt.name" . }}
  labels: {{ include "openstack-cluster.componentLabels" (list . "control-plane") | nindent 4 }}
  annotations:
    {{ .Values.projectPrefix }}/template-checksum: {{ include "openstack-cluster.controlplane.mt.checksum" . }}
    # Cluster API complains when old templates disappear before it has rolled all the machines over
    # When deploying with Helm, leave the resource behind and let Cluster API clean it up
    helm.sh/resource-policy: keep
    # Allow Argo to clean up old templates by ignoring the non-controller owner references,
    #Â but only after the cluster has become healthy again
    argocd.argoproj.io/sync-options: "ControllerReferencesOnly=true,PruneLast=true"
spec:
  {{- include "openstack-cluster.controlplane.mt.spec" . | nindent 2 }}
