{{/*
  Machine templates are immutable, so we need to make a new one when the spec changes.
  To do this, we create a new template whenever the checksum of the spec changes.
*/}}
{{- define "openstack-cluster.controlplane.mt.spec" -}}
template:
  spec:
    identityRef:
      kind: Secret
      name: {{ include "openstack-cluster.cloudCredentialsSecretName" . }}
    cloudName: openstack
    flavor: {{ .Values.controlPlane.machineFlavor | required ".Values.controlPlane.machineFlavor is required" }}
    {{- with .Values.machineSSHKeyName }}
    sshKeyName: {{ . }}
    {{- end }}
    {{- if .Values.controlPlane.machineRootVolume.diskSize }}
    rootVolume: {{ toYaml .Values.controlPlane.machineRootVolume | nindent 6 }}
    {{- end }}
    {{- if .Values.machineImageId }}
    imageUUID: {{ .Values.machineImageId }}
    {{- else if .Values.machineImage }}
    image: {{ tpl .Values.machineImage . }}
    {{- else }}
    {{- fail "Either machineImage or machineImageId is required" }}
    {{- end }}
    {{- with .Values.controlPlane.machineNetworking.networks }}
    networks: {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.controlPlane.machineNetworking.ports }}
    ports: {{ toYaml . | nindent 6 }}
    {{- end }}
{{- end }}

{{- define "openstack-cluster.controlplane.mt.checksum" -}}
{{- include "openstack-cluster.controlplane.mt.spec" . | sha256sum }}
{{- end }}

{{- define "openstack-cluster.controlplane.mt.name" -}}
{{- $checksum := include "openstack-cluster.controlplane.mt.checksum" . }}
{{- include "openstack-cluster.componentName" (list . "control-plane") }}-{{ trunc 8 $checksum }}
{{- end }}

apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackMachineTemplate
metadata:
  name: {{ include "openstack-cluster.controlplane.mt.name" . }}
  labels: {{ include "openstack-cluster.componentLabels" (list . "control-plane") | nindent 4 }}
  annotations:
    {{ .Values.projectPrefix }}/template-checksum: {{ include "openstack-cluster.controlplane.mt.checksum" . }}
    # Cluster API complains when old templates disappear before it has rolled all the machines over
    # When deploying with Helm, leave the resource behind and let Cluster API clean it up
    helm.sh/resource-policy: keep
    # Allow Argo to clean up old templates by ignoring the non-controller owner references,
    #Â but only after the cluster has become healthy again
    argocd.argoproj.io/sync-options: "ControllerReferencesOnly=true,PruneLast=true"
spec:
  {{- include "openstack-cluster.controlplane.mt.spec" . | nindent 2 }}
