docker.io:
  images:
    grafana/grafana:
    - 12.3.3
ghcr.io:
  images:
    jkroepke/kube-webhook-certgen:
    - 1.7.7
quay.io:
  images:
    kiwigrid/k8s-sidecar:
    - 2.5.0
    prometheus-operator/prometheus-config-reloader:
    - v0.88.1
    prometheus-operator/prometheus-operator:
    - v0.88.1
    prometheus/alertmanager:
    - v0.31.1
    prometheus/node-exporter:
    - v1.10.2
    prometheus/prometheus:
    - v3.9.1
    thanos/thanos:
    - v0.41.0
registry.k8s.io:
  images:
    kube-state-metrics/kube-state-metrics:
    - v2.18.0
