docker.io:
  images:
    grafana/grafana:
    - 12.3.0
ghcr.io:
  images:
    jkroepke/kube-webhook-certgen:
    - 1.7.3
quay.io:
  images:
    kiwigrid/k8s-sidecar:
    - 2.1.2
    prometheus-operator/prometheus-config-reloader:
    - v0.87.1
    prometheus-operator/prometheus-operator:
    - v0.87.1
    prometheus/alertmanager:
    - v0.30.0
    prometheus/node-exporter:
    - v1.10.2
    prometheus/prometheus:
    - v3.8.1
    thanos/thanos:
    - v0.40.1
registry.k8s.io:
  images:
    kube-state-metrics/kube-state-metrics:
    - v2.17.0
