---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: {{ include "openstack-cluster.clusterName" . }}
  labels: {{ include "openstack-cluster.labels" . | nindent 4 }}
  annotations:
    #Â We let Cluster API clean up this resource
    # Deleting it ourselves, which CAPI is not expecting, can cause some nasty race conditions
    helm.sh/resource-policy: keep
    # NOTE: Argo won't delete this object itself as it has an owner reference to the cluster
spec:
  identityRef:
    name: {{ include "openstack-cluster.cloudCredentialsSecretName" . }}
    cloudName: openstack
  {{- with .Values.controlPlaneEndpoint }}
  controlPlaneEndpoint: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.clusterNetworking }}
  {{- if .manageSecurityGroups }}
  managedSecurityGroups:
    allowAllInClusterTraffic: {{ .allowAllInClusterTraffic }}
  {{- end }}
  {{- with .externalNetworkId }}
  externalNetwork:
    id: {{ . }}
  {{- end }}
  {{- with .internalNetwork }}
  {{- if or .networkFilter .subnetFilter }}
  {{- with .networkFilter }}
  network: {{ include "openstack-cluster.convert.neutronFilter" . | nindent 4 }}
  {{- end }}
  {{- with .subnetFilter }}
  subnets:
    - {{ include "openstack-cluster.convert.neutronFilter" . | nindent 6 }}
  {{- end }}
  {{- else }}
  managedSubnets:
    - cidr: {{ .nodeCidr }}
      {{- with .dnsNameservers }}
      dnsNameservers: {{ toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- with .Values.apiServer }}
  {{- if .enableLoadBalancer }}
  apiServerLoadBalancer:
    enabled: true
    {{- if .loadBalancerProvider }}
    provider: {{ .loadBalancerProvider }}
    {{- end }}
    {{- if .allowedCidrs }}
    allowedCidrs:
      {{- range .allowedCidrs }}
      - {{ . }}
      {{- end}}
    {{- end }}
  {{- end }}
  disableAPIServerFloatingIP: {{ not .associateFloatingIP }}
  {{- with .floatingIP }}
  apiServerFloatingIP: {{ . }}
  {{- end }}
  {{- with .fixedIP }}
  apiServerFixedIP: {{ . }}
  {{- end }}
  apiServerPort: {{ .port }}
  {{- end }}
  {{- with .Values.controlPlane }}
  {{- if .omitFailureDomain }}
  controlPlaneOmitAvailabilityZone: true
  {{- else if .failureDomains }}
  controlPlaneAvailabilityZones: {{ toYaml .failureDomains | nindent 4 }}
  {{- end }}
  {{- end }}
