{{- if and .Values.monitoring.enabled .Values.monitoring.alloy.enabled }}
# TODO: Update this to include Loki v3 once the new addon is available
{{- if .Values.monitoring.lokiStack.enabled }}
{{- fail (printf "Cannot enable both 'lokiStack' and 'loki_v2' addons simultaneously; please choose one.") }}
{{- end }}
{{- if .Values.monitoring.promtail.enabled }}
{{- fail (printf "Cannot enable both 'promtail' and 'alloy' addons simultaneously; please choose one.") }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-addons.componentName" (list . "alloy") }}-config
  labels:
    {{- include "cluster-addons.componentLabels" (list . "alloy") | nindent 4 }}
    addons.stackhpc.com/watch: ""
stringData:
  defaults: |
    serviceMonitor:
      enabled: true
    alloy:
      configMap:
        create: true
        content: |
          discovery.kubernetes "kubernetes_pods" {
            role = "pod"
          }
          discovery.relabel "kubernetes_pods" {
            targets = discovery.kubernetes.kubernetes_pods.targets
            rule {
              source_labels = ["__meta_kubernetes_pod_controller_name"]
              regex         = "([0-9a-z-.]+?)(-[0-9a-f]{8,10})?"
              target_label  = "__tmp_controller_name"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name", "__meta_kubernetes_pod_label_k8s_app","__meta_kubernetes_pod_label_app", "__tmp_controller_name", "__meta_kubernetes_pod_name"]
              regex         = "^;*([^;]+)(;.*)?$"
              target_label  = "app"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_instance", "__meta_kubernetes_pod_label_instance"]
              regex         = "^;*([^;]+)(;.*)?$"
              target_label  = "instance"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_component", "__meta_kubernetes_pod_label_component"]
              regex         = "^;*([^;]+)(;.*)?$"
              target_label  = "component"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              target_label  = "node_name"
            }
            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              target_label  = "namespace"
            }
            rule {
              source_labels = ["namespace", "app"]
              separator     = "/"
              target_label  = "job"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label  = "pod"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label  = "container"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
              separator     = "/"
              target_label  = "__path__"
              replacement   = "/var/log/pods/*$1/*.log"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash", "__meta_kubernetes_pod_annotation_kubernetes_io_config_hash", "__meta_kubernetes_pod_container_name"]
              separator     = "/"
              regex         = "true/(.*)"
              target_label  = "__path__"
              replacement   = "/var/log/pods/*$1/*.log"
            }
          }
          local.file_match "kubernetes_pods" {
            path_targets = discovery.relabel.kubernetes_pods.output
          }
          loki.process "kubernetes_pods" {
            forward_to = [loki.write.default.receiver]
            stage.cri { }
          }
          loki.source.file "kubernetes_pods" {
            targets               = local.file_match.kubernetes_pods.targets
            forward_to            = [loki.process.kubernetes_pods.receiver]
            legacy_positions_file = "/run/promtail/positions.yaml"
          }
          discovery.relabel "journal" {
            targets = []
            rule {
              source_labels = ["__journal__systemd_unit"]
              target_label  = "unit"
            }
            rule {
              source_labels = ["__journal__hostname"]
              target_label  = "hostname"
            }
            rule {
              source_labels = ["__journal_priority_keyword"]
              target_label  = "level"
            }
          }
          loki.source.journal "journal" {
            max_age       = "12h0m0s"
            path          = "/var/log/journal"
            relabel_rules = discovery.relabel.journal.rules
            forward_to    = [loki.write.default.receiver]
            labels        = {
              job = "systemd-journal",
            }
          }
          loki.write "default" {
            endpoint {
    {{- if .Values.monitoring.alloy.clients }}
                  url       = "{{ (index .Values.monitoring.alloy.clients 0).url }}"
                  tenant_id = {{ (index .Values.monitoring.alloy.clients 0).tenant_id }}
    {{- else }}
                  url       = "http://loki.monitoring-system.svc:3100/loki/api/v1/push"
                  tenant_id = 1
    {{- end }}
            }
            external_labels = {}
          }
      mounts:
        extra:
          - name: journal
            mountPath: /var/log/journal
            readOnly: true
          - name: pods
            mountPath: /var/log/pods
            readOnly: true
          - name: machine-id
            mountPath: /etc/machine-id
            readOnly: true
    controller:
      volumes:
        extra:
          - name: journal
            hostPath:
              path: /var/log/journal
          - name: pods
            hostPath:
              path: /var/log/pods
          - name: machine-id
            hostPath:
              path: /etc/machine-id
  overrides: |
    {{- toYaml .Values.monitoring.alloy.release.values | nindent 4 }}

---
apiVersion: addons.stackhpc.com/v1alpha1
kind: HelmRelease
metadata:
  name: {{ include "cluster-addons.componentName" (list . "alloy") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "alloy") | nindent 4 }}
spec:
  clusterName: {{ include "cluster-addons.clusterName" . }}
  bootstrap: true
  chart: {{ toYaml .Values.monitoring.alloy.chart | nindent 4 }}
  targetNamespace: {{ .Values.monitoring.alloy.release.namespace }}
  releaseName: alloy
  valuesSources:
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "alloy") }}-config
        key: defaults
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "alloy") }}-config
        key: overrides
{{- end }}
ubuntu@azimuth-jas-loki:~/capi-helm-charts/charts/cluster-addons/templates/monitoring$ 
ubuntu@azimuth-jas-loki:~/capi-helm-charts/charts/cluster-addons/templates/monitoring$ cat loki-v3.yaml 
{{- if and .Values.monitoring.enabled .Values.monitoring.loki_v3.enabled }}
# TODO: Update this to include Loki v3 once the new addon is available
{{- if .Values.monitoring.lokiStack.enabled }}
{{- fail (printf "Cannot enable both 'lokiStack' and 'loki' addons simultaneously; please choose one.") }}
{{- end }}
{{- if .Values.monitoring.loki_v2.enabled }}
{{- fail (printf "Cannot enable both 'loki_v2' and 'loki_v3' addons simultaneously; please choose one.") }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-addons.componentName" (list . "loki-v3") }}-config
  labels:
    {{- include "cluster-addons.componentLabels" (list . "loki-v3") | nindent 4 }}
    addons.stackhpc.com/watch: ""
stringData:
  defaults: |
    monitoring:
      serviceMonitor:
        enabled: true
      dashboards:
        enabled: false
    {{- if not .Values.monitoring.loki_v3.release.values.singleBinary.persistence.enabled }}
    # Default Loki container user cannot write to container's /var/loki so use emptyDir instead
    singleBinary:
      extraVolumes:
        - name: loki
          emptyDir: {}
      extraVolumeMounts:
        - name: loki
          mountPath: /var/loki
    {{- end }}
  overrides: |
    {{- toYaml .Values.monitoring.loki_v3.release.values | nindent 4 }}
---
apiVersion: addons.stackhpc.com/v1alpha1
kind: HelmRelease
metadata:
  name: {{ include "cluster-addons.componentName" (list . "loki-v3") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "loki-v3") | nindent 4 }}
spec:
  clusterName: {{ include "cluster-addons.clusterName" . }}
  bootstrap: true
  chart: {{ toYaml .Values.monitoring.loki_v3.chart | nindent 4 }}
  targetNamespace: {{ .Values.monitoring.loki_v3.release.namespace }}
  releaseName: loki
  valuesSources:
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "loki-v3") }}-config
        key: defaults
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "loki-v3") }}-config
        key: overrides
  # StatefulSets do not allow their PVCs to be resized, but we can use lifecycle hooks
  # to ensure that it happens correctly
  lifecycleHooks:
    preUpgrade:
      - apiVersion: apps/v1
        kind: StatefulSet
        name: loki
        action: delete
    {{- if .Values.monitoring.loki_v3.release.values.singleBinary.persistence.enabled }}
      - apiVersion: v1
        kind: PersistentVolumeClaim
        selector:
          app.kubernetes.io/instance: loki
          app.kubernetes.io/name: loki
        action: patch
        options:
          data:
            spec:
              resources:
                requests:
                  storage: {{ .Values.monitoring.loki_v3.release.values.singleBinary.persistence.size }}
    {{- else }}
    postUpgrade:
      - apiVersion: v1
        kind: PersistentVolumeClaim
        selector:
          app.kubernetes.io/instance: loki
          app.kubernetes.io/name: loki
        action: delete
    {{- end }}
---
apiVersion: addons.stackhpc.com/v1alpha1
kind: Manifests
metadata:
  name: {{ include "cluster-addons.componentName" (list . "loki-dashboards") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "loki-dashboards") | nindent 4 }}
spec:
  clusterName: {{ include "cluster-addons.clusterName" . }}
  bootstrap: true
  targetNamespace: {{ .Values.monitoring.loki_v3.release.namespace }}
  releaseName: loki-dashboards
  manifestSources:
    - template: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: loki-grafana-datasource
          labels:
            grafana_datasource: "1"
        data:
          loki-datasource.yaml: |-
            apiVersion: 1
            datasources:
              - name: Loki
                type: loki
                {{- with .Values.monitoring.loki_v3 }}
                url: http://{{ .release.values.fullnameOverride | default .chart.name }}.{{ .release.namespace }}:3100
                {{- end }}
                access: proxy
                version: 1
                isDefault: false
    - template: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: loki-grafana-dashboards
          labels:
            grafana_dashboard: "1"
        data:
          loki-pod-logs-dashboard.json: |
            {% raw %}
            {{- .Files.Get "grafana-dashboards/loki-pod-logs-dashboard.json" | nindent 12 }}
            {% endraw %}
          loki-systemd-logs-dashboard.json: |
            {% raw %}
            {{- .Files.Get "grafana-dashboards/loki-systemd-logs-dashboard.json" | nindent 12 }}
            {% endraw %}
          loki-metrics-dashboard.json: |
            {% raw %}
            {{- .Files.Get "grafana-dashboards/loki-metrics-dashboard.json" | nindent 12 }}
            {% endraw %}
{{- end }}